language: node_js

node_js:
- node
- 'lts/*'

cache: npm

addons:
  sonarcloud:
    organization: "dw1a3"
    token: ${SONAR_TOKEN}

script:
  # the following command line builds the project, runs the tests with coverage and then execute the SonarCloud analysis
  - sonar-scanner -X 
  - sonar.host.url = https://sonarcloud.io/ 
  - sonar.projectKey = jeffersonss999_node_js-example


  